# ----
# Site (블로그)

title: 내가 보려고 만든 블로그
url: "https://mooooonmin.github.io"
baseurl: ""
google_analytics_key:
encoding: utf-8
timezone: Asia/Seoul

# SEO (jekyll-seo-tag)
logo: /siteicon.png
description:
author:
  name: mooooonmin
  email: mooooonmin@gmail.com
social:
  name: ""
  links: []

# -----
# Build

permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - serve.sh

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: default
